### ISSUE TITLE
Uncaught TypeError: packageJSON.repository.replace is not a function

### ISSUE THREAD

**Issue by af6140** [liuderchi/ide-yaml#15]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [ide-yaml](https://github.com/liuderchi/ide-yaml) package 0.4.0

### Stack Trace

Uncaught TypeError: packageJSON.repository.replace is not a function

```
At /home/dwang/.atom/packages/ide-yaml/src/help_cmd.js:16

TypeError: packageJSON.repository.replace is not a function
    at NotificationElement.onDidClick (/packages/ide-yaml/src/help_cmd.js:16:70)
    at HTMLAnchorElement.<anonymous> (/usr/share/atom/resources/app/node_modules/notifications/lib/notification-element.js:135:48)
```

### Commands

```
  4x -9:01.0 core:backspace (input.hidden-input)
     -8:58.7.0 intentions:highlight (input.hidden-input)
     -8:58.3.0 core:save (input.hidden-input)
  2x -8:26.3.0 intentions:highlight (input.hidden-input)
     -8:20.5.0 core:copy (input.hidden-input)
     -1:11.9.0 tabs:close-all-tabs (div.title.icon.database-icon.medium-yellow)
     -0:56.5.0 grammar-selector:show (atom-text-editor.editor.enable-atom-ide-find-references.is-focused)
  4x -0:52.9.0 core:backspace (input.hidden-input)
     -0:51.4.0 editor:consolidate-selections (input.hidden-input)
     -0:51.4.0 core:cancel (input.hidden-input)
     -0:26.6.0 intentions:highlight (input.hidden-input)
     -0:26.2.0 command-palette:toggle (input.hidden-input)
     -0:19.6.0 core:confirm (input.hidden-input)
     -0:19.6.0 ide-yaml:help (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.5.1 
busy-signal 1.4.3 
eyaml-profiles 0.1.0 
file-icons 2.1.13 
go-debug 1.5.2 
go-plus 5.5.6 
go-signature-statusbar 1.2.3 
ide-go 0.4.0 
ide-json 0.1.0 
ide-yaml 0.4.0 
intentions 1.1.5 
language-elixir 0.20.3 
language-puppet 0.23.0 
language-terraform 0.8.1 
linter 2.2.0 
linter-ui-default 1.6.10 
nuclide 0.260.0 
platformio-ide-terminal 2.7.0 
```

**Comment by liuderchi** [comment]
@af6140 Thanks for reporting this bug.
It's about missing fields in `package.json` after package publishment.
