### ISSUE TITLE
After uninstall ide-yaml still breaks outline view

### ISSUE THREAD

**Issue by waldnzwrld** [liuderchi/ide-yaml#9]
IDE-YAML was causing issues with other ide packages. I uninstalled it, and am now presented with errors pertaining to ide-yaml even though the ide-yaml directory and package no longer exist in my system. This seems to indicate modifications which were not reverted on uninstall. 

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13
**Thrown From**: 'ide-yaml' package vundefined

### Stack Trace

Uncaught Error: Connection is closed.

```
At .atom/packages/ide-yaml/node_modules/vscode-jsonrpc/lib/main.js:606

Error: Connection is closed.
    at /packages/ide-yaml/node_modules/vscode-jsonrpc/lib/main.js:131:28)
    at throwIfClosedOrDisposed (/packages/ide-yaml/node_modules/vscode-jsonrpc/lib/main.js:606:19)
    at Object.sendNotification (/packages/ide-yaml/node_modules/vscode-jsonrpc/lib/main.js:660:13)
    at LanguageClientConnection._sendNotification (/packages/ide-yaml/node_modules/atom-languageclient/build/lib/languageclient.js:244:15)
    at LanguageClientConnection.didChangeTextDocument (/packages/ide-yaml/node_modules/atom-languageclient/build/lib/languageclient.js:133:10)
    at TextEditorSyncAdapter.sendFullChanges (/packages/ide-yaml/node_modules/atom-languageclient/build/lib/adapters/document-sync-adapter.js:183:22)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:636:38
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayLayer.reset (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:87:26)
    at TextEditor.module.exports.TextEditor.update (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:532:31)
    at TextEditor.module.exports.TextEditor.setEditorWidthInChars (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:897:25)
    at TextEditorComponent.updateModelSoftWrapColumn (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2114:30)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:368:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:275:16)
    at etch.getScheduler.updateDocument (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:225:46)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:187:15)
    at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:65
```
![monosnap 2017-10-09 12-50-17](https://user-images.githubusercontent.com/4338862/31355772-6b7c8458-acf0-11e7-9bed-8475eb4972bf.png)

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-handlebars 1.3.0 
atom-ide-ui 0.4.0 
atom-material-syntax 1.0.6 
autoclose-html 0.23.0 
autocorrect 0.0.4 
autocorrect-en 0.0.3 
busy-signal 1.4.3 
docker 0.8.0 
flex-tab-bar 1.0.1 
fold-lines 0.2.2 
git-history 3.3.0 
git-log 0.4.1 
git-plus 7.9.3 
git-status 0.3.4 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
ide-css 0.2.0 
ide-ember 0.4.2 
ide-html 0.3.0 
ide-json 0.1.0 
ide-typescript 0.6.1 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.3.2 
linter-handlebars 2.5.0 
linter-js-yaml 1.2.8 
linter-rubocop 2.2.0 
linter-ruby 1.2.6 
linter-tidy 2.3.1 
linter-ui-default 1.6.10 
markdown-preview-enhanced 0.14.11 
markdown-table-editor 0.6.4 
merge-conflicts 1.4.5 
minimap-plus 4.29.2 
monokai-seti 0.9.0 
platformio-ide-terminal 2.7.0 
project-manager 3.3.5 
ruby-block 0.3.6 
ruby-navigator 0.5.0 
ruby-test 1.0.2 
seeing-is-believing 2.2.3 
seti-ui 1.9.0 
split-diff 1.5.1 
tester 1.4.0 
tester-mocha 1.0.0 
```

**Comment by liuderchi** [comment]
@waldnzwrld Thanks for reporting this critical bug.
Please terminate Atom app and start it again, which is a current workaround.

This is an ipc issue about connection is not closed properly.

TODO for myself
  - close connection before uninstallation, or prompt restart after uninstallation

**Comment by waldnzwrld** [comment]
Hey @liuderchi I did restart however the issue persisted. I removed cached storage for Atom and was then able to successfully relaunch the ide features (including some of your other excellent packages) 

Thank you for the 👀

**Comment by liuderchi** [comment]
>  I removed cached storage for Atom and ...

Do you mean `~/.atom/storage/application.json` ?

**Comment by waldnzwrld** [comment]
@liuderchi I removed the `~/Library/Application Support/Atom` directory then restarted Atom.

I know this is somewhat of a brute force approach.

**Comment by liuderchi** [comment]
@waldnzwrld Thanks for sharing. 
I ran into this issue recently and still try to reproduce it.
This is brute force but now helpful to reset my environment. 👍

**Comment by brianmhunt** [comment]
This breaks Atom.  *Completely.*

For me, the error pops up and steals focus at every single keystroke, and interrupts that keystroke so it never actually happens.  Breaks. Atom.

I tried uninstall `ide-yaml`, removing the paths @waldnzwrld suggested, and removing every package and re-installing atom, and this error still occurs.

```
/Users/bmh/.atom/packages/ide-yaml/node_modules/vscode-jsonrpc/lib/main.js:606
Hide Stack Trace
Error: Connection is closed.
    at new ConnectionError (/Users/bmh/.atom/packages/ide-yaml/node_modules/vscode-jsonrpc/lib/main.js:131:28)
    at throwIfClosedOrDisposed (/Users/bmh/.atom/packages/ide-yaml/node_modules/vscode-jsonrpc/lib/main.js:606:19)
    at Object.sendNotification (/Users/bmh/.atom/packages/ide-yaml/node_modules/vscode-jsonrpc/lib/main.js:660:13)
    at LanguageClientConnection._sendNotification (/Users/bmh/.atom/packages/ide-yaml/node_modules/atom-languageclient/build/lib/languageclient.js:244:15)
    at LanguageClientConnection.didChangeTextDocument (/Users/bmh/.atom/packages/ide-yaml/node_modules/atom-languageclient/build/lib/languageclient.js:133:10)
    at TextEditorSyncAdapter.sendFullChanges (/Users/bmh/.atom/packages/ide-yaml/node_modules/atom-languageclient/build/lib/adapters/document-sync-adapter.js:183:22)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:626:38
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayLayer.emitDidChangeSyncEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:825:24)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:780:35
    at Map.forEach (native)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:779:47)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:762:18)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1001:22)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:955:20)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1234:30
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2617:49)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2583:41)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1232:25)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1198:25)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1630:30)
```

Crazy. 😄 

Will be using Sublime in the interim.  I hope you're able to fix it — not sure how many others are affected.

Happy to give some debugging info if you think that'll help.

**Comment by waldnzwrld** [comment]
@brianmhunt try removing these directories

```
~/Library/Application\ Support/Atom
~/Library/Application\ Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.github.atom.sfl2
~/Library/Saved\ Application\ State/com.github.atom.savedState
~/Library/Caches
```

Restart your 🍎  after that and see if you are still seeing  the error

**Comment by brianmhunt** [comment]
@waldnzwrld I'm sorry to report that the above did not remedy the issue.  ide-yaml is not installed, all the directories were deleted, and I restarted the 🍎.  Opening a .js file and the error occurred near-immediately.  Atom is bricked. 🎃

**Comment by brianmhunt** [comment]
This may be related to https://github.com/OmniSharp/atom-languageclient/issues/1#issuecomment-329362223

**Comment by liuderchi** [comment]
> This may be related to https://github.com/OmniSharp/atom-languageclient/issues/1#issuecomment-329362223

@brianmhunt 
  - Did you recover Atom from bricked by following those steps in the comment?
  - Did this error happen again with *ide-yaml v0.4.1* ? 
      - ide-yaml v0.4.1 takes `vscode-jsonrpc@3.3.1`

**Comment by brianmhunt** [comment]
@liuderchi 

Since reading your comment I *appear* (hesitantly) to have unbricked Atom by unzipping the linked `vscode-jsonrpc@3.4.0` into `~/.atom/packages/ide-yaml/node_modules` (i.e. replacing `@3.4.1`).

I also performed the changes to `atom-languageclient`.

Will report any regression.

**Comment by brianmhunt** [comment]
@waldnzwrld @liuderchi Did one of you want to do a screen share from my machine so we can debug my symptomatic instance? (Or invite someone else)

**Comment by liuderchi** [comment]
@brianmhunt sorry for late response. Does this still happen now?

**Comment by liuderchi** [comment]
@waldnzwrld 
> I removed the `~/Library/Application Support/Atom` and the `~/Library/Saved Application State/com.github.atom.com` directories then restarted Atom.

I came across this similar issue today from `ide-typescript` and I found another similar workaround.

Assuming 
  * you already got some project folders in tree view when issue happens
  * by your Atom config, Atom tries to restore previous window state when the app starts

the workaround is

> just add one arbitrary project folder to tree view then do `Window: Reload`

Perhaps this gives a clue that this issue is related to *specific Atom window*
I got 2 windows with both js codes opened, but error message jumps in only one window.

**Comment by brianmhunt** [comment]
@liuderchi I've lost the setup that was breaking - I reinstalled everything from scratch, basically, so I'm unable to reproduce at the moment.  However if I do encounter it I will update.

**Comment by andi-dev** [comment]
I just ran into the same issue, however it was the mentioned error that made me uninstall the ide-yaml package. Now, after uninstalling and following the suggestions  above, I still get the same errors as soon as I try to save any js file...

**Comment by andi-dev** [comment]
I also really don't get how that error can come from a file that doesn't exist anymore..

**Comment by liuderchi** [comment]
@andi-dev please help with following steps

1. quit atom app
2. in shell run `ls ~/.atom/packages/ide-yaml` to confirm ide-yaml folder is removed
3. if not, please do `rm -rf ~/.atom/packages/ide-yaml`
4. start atom again. Hopefully this will help remove ide-yaml successfully
